print(type( 3 ))
print(type( 3.14 ))
print(type( "Bonjour" ))
print(type( "A" ))
print(type( 2 * 3.5 ))
print(type( 2 + 5 ))
print(type( 10 / 3 ))
print(type( 10 // 3 ))
print(type( int("8") ))
print(type( float("8") ))
print(type( chr(65) ))
